import {
  IconArmchair,
  IconBabyCarriage,
  IconBallFootball,
  IconBarbell,
  IconBolt,
  IconBook,
  IconBriefcase2,
  IconBuildingBank,
  IconBuildingSkyscraper,
  IconCar,
  IconCash,
  IconCoffee,
  IconCoin,
  IconCreditCard,
  IconCurrencyBitcoin,
  IconDeviceGamepad2,
  IconDeviceLaptop,
  IconDeviceTv,
  IconDroplet,
  IconFileInvoice,
  IconFolder,
  IconGasStation,
  IconGift,
  IconHeartbeat,
  IconHeartHandshake,
  IconHome,
  IconMovie,
  IconMusic,
  IconParking,
  IconPaw,
  IconPigMoney,
  IconPill,
  IconPlane,
  IconReceipt2,
  IconReceiptRefund,
  IconRepeat,
  IconShieldCheck,
  IconShirt,
  IconShoppingBag,
  IconStar,
  IconToolsKitchen2,
  IconTrendingUp,
  IconWallet,
  IconWashMachine,
  IconWifi,
  type TablerIcon,
} from '@/components/icons';

// Mirror family-finance-app/lib/constants/category-icons.tsx — key disimpan di
// `categories.icon`, jadi harus sama persis dengan versi web.
export const CATEGORY_ICON_OPTIONS: { key: string; label: string; Icon: TablerIcon }[] = [
  { key: 'food', label: 'Makanan', Icon: IconToolsKitchen2 },
  { key: 'transport', label: 'Transportasi', Icon: IconCar },
  { key: 'bills', label: 'Tagihan', Icon: IconReceipt2 },
  { key: 'education', label: 'Pendidikan', Icon: IconBook },
  { key: 'health', label: 'Kesehatan', Icon: IconHeartbeat },
  { key: 'entertainment', label: 'Hiburan', Icon: IconMovie },
  { key: 'shopping', label: 'Belanja', Icon: IconShoppingBag },
  { key: 'debt', label: 'Cicilan/Utang', Icon: IconCreditCard },
  { key: 'donation', label: 'Donasi', Icon: IconGift },
  { key: 'home', label: 'Rumah', Icon: IconHome },
  { key: 'salary', label: 'Gaji', Icon: IconBriefcase2 },
  { key: 'bonus', label: 'Bonus', Icon: IconStar },
  { key: 'investment', label: 'Investasi', Icon: IconTrendingUp },
  { key: 'gift', label: 'Hadiah', Icon: IconGift },
  { key: 'bank', label: 'Transfer', Icon: IconBuildingBank },
  { key: 'cash', label: 'Tunai', Icon: IconCash },
  { key: 'wallet', label: 'Dompet', Icon: IconWallet },
  { key: 'folder', label: 'Umum', Icon: IconFolder },
  { key: 'fuel', label: 'Bensin', Icon: IconGasStation },
  { key: 'parking', label: 'Parkir', Icon: IconParking },
  { key: 'phone', label: 'Pulsa/Data', Icon: IconWifi },
  { key: 'electricity', label: 'Listrik', Icon: IconBolt },
  { key: 'water', label: 'Air', Icon: IconDroplet },
  { key: 'rent', label: 'Sewa', Icon: IconBuildingSkyscraper },
  { key: 'coffee', label: 'Kopi/Jajan', Icon: IconCoffee },
  { key: 'pet', label: 'Hewan Peliharaan', Icon: IconPaw },
  { key: 'baby', label: 'Anak/Bayi', Icon: IconBabyCarriage },
  { key: 'travel', label: 'Perjalanan', Icon: IconPlane },
  { key: 'fitness', label: 'Olahraga', Icon: IconBarbell },
  { key: 'sport', label: 'Hobi Olahraga', Icon: IconBallFootball },
  { key: 'pharmacy', label: 'Obat', Icon: IconPill },
  { key: 'insurance', label: 'Asuransi', Icon: IconShieldCheck },
  { key: 'subscription', label: 'Langganan', Icon: IconRepeat },
  { key: 'laundry', label: 'Cuci/Laundry', Icon: IconWashMachine },
  { key: 'clothes', label: 'Pakaian', Icon: IconShirt },
  { key: 'electronics', label: 'Elektronik', Icon: IconDeviceTv },
  { key: 'furniture', label: 'Perabotan', Icon: IconArmchair },
  { key: 'music', label: 'Musik', Icon: IconMusic },
  { key: 'game', label: 'Game', Icon: IconDeviceGamepad2 },
  { key: 'freelance', label: 'Freelance', Icon: IconDeviceLaptop },
  { key: 'dividend', label: 'Dividen', Icon: IconCoin },
  { key: 'crypto', label: 'Kripto', Icon: IconCurrencyBitcoin },
  { key: 'savings', label: 'Tabungan', Icon: IconPigMoney },
  { key: 'charity', label: 'Amal/Sosial', Icon: IconHeartHandshake },
  { key: 'refund', label: 'Refund', Icon: IconReceiptRefund },
  { key: 'invoice', label: 'Tagihan/Faktur', Icon: IconFileInvoice },
];

// Lookup statis key → komponen ikon (objek, bukan fungsi, supaya aman dipakai saat render).
export const CATEGORY_ICONS: Record<string, TablerIcon | undefined> = Object.fromEntries(
  CATEGORY_ICON_OPTIONS.map((o) => [o.key, o.Icon])
);
